#!/usr/bin/env python3
# =============================================================================
# scripts/gen_vol_test_vectors.py -- Reference vectors for realized_vol tests
# =============================================================================
#
# Generates deterministic log-return arrays + expected annualized-vol values
# for the Rust unit tests in programs/opta/src/state/vol_oracle.rs. Output
# is copy-pasted into the test file as `const` arrays / values.
#
# Pure-stdlib (no numpy) so this runs on minimal Python installs. Uses
# Python's `random.gauss` (Mersenne Twister; deterministic with seed())
# for normal returns. Sample variance computed by hand with ddof=1.
#
# Math reference (must match the on-chain implementation):
#   - Sample variance: var = sum((x - mean)^2) / (n - 1) (matches Deribit
#     DVOL and industry standard; matches numpy.var(ddof=1))
#   - Annualization: sigma_annual = sigma_hourly * sqrt(8760)
#   - SCALE = 1e12 (solmath fixed-point convention)
#
# Determinism: each scenario seeds `random` explicitly so re-running the
# script produces the same outputs. Tolerance from the on-chain integer
# math is bounded at 0.1% per the Stage B prompt (read-side gate is
# audited against these values).
#
# Regenerate after any change to the on-chain math: re-run, copy the
# printed arrays/constants verbatim into the test file.
#
# Run via: wsl -e bash -lc "python3 scripts/gen_vol_test_vectors.py"
# =============================================================================

import math
import random

SCALE = 10**12
HOURS_PER_YEAR = 8760  # 24 * 365


def scaled_int(x: float) -> int:
    """Round-to-nearest float -> i64 at SCALE."""
    return int(round(x * SCALE))


def sample_variance(xs: list[float]) -> float:
    """Sample variance (ddof=1). Matches numpy.var(xs, ddof=1)."""
    n = len(xs)
    if n < 2:
        return 0.0
    mean = sum(xs) / n
    return sum((x - mean) ** 2 for x in xs) / (n - 1)


def annualized_vol(returns: list[float]) -> float:
    """Annualized sigma of hourly log returns."""
    return math.sqrt(sample_variance(returns)) * math.sqrt(HOURS_PER_YEAR)


def emit_array(label: str, arr: list[int]) -> None:
    """Print a Rust-friendly const i64 array."""
    print(f"const {label}: [i64; {len(arr)}] = [")
    # 8 per line for readability
    for i in range(0, len(arr), 8):
        chunk = arr[i:i + 8]
        print("    " + ", ".join(str(x) for x in chunk) + ",")
    print("];")
    print()


def main() -> None:
    print("// =============================================================")
    print("// AUTO-GENERATED by scripts/gen_vol_test_vectors.py")
    print(f"// Regenerated 2026-05-17 -- copy verbatim into vol_oracle.rs tests")
    print("// =============================================================")
    print()

    # --- Vector 1: pseudo-random returns ~ N(0, 0.01) over 200 samples ---
    # Models ~93% annual vol (sigma_hourly = 0.01 -> annual = 0.01 * sqrt(8760)).
    # Stage B Step 4 critical-correctness test.
    random.seed(42)
    v1_returns_float = [random.gauss(0.0, 0.01) for _ in range(200)]
    v1_returns_scaled = [scaled_int(r) for r in v1_returns_float]
    v1_expected_float = annualized_vol(v1_returns_float)

    # Cross-check: also compute from the round-tripped scaled returns to
    # bound the "Python float -> SCALE int -> back to float" loss. The
    # on-chain function never sees the original floats; it sees these ints.
    v1_returns_back = [r / SCALE for r in v1_returns_scaled]
    v1_expected_from_scaled = annualized_vol(v1_returns_back)
    v1_expected_from_scaled_int = scaled_int(v1_expected_from_scaled)
    v1_sum = sum(v1_returns_scaled)
    v1_sum_sq = sum(x * x for x in v1_returns_scaled)

    emit_array("V1_RETURNS", v1_returns_scaled)
    print(f"// Vector 1 (200 samples, N(0, 0.01)):")
    print(f"//   annualized sigma (float math):       {v1_expected_float:.12f}")
    print(f"//   annualized sigma (round-trip math):  {v1_expected_from_scaled:.12f}")
    print(f"const V1_SAMPLE_COUNT: u16 = {len(v1_returns_scaled)};")
    print(f"const V1_SUM_LOG_RETURNS: i128 = {v1_sum};")
    print(f"const V1_SUM_LOG_RETURNS_SQ: i128 = {v1_sum_sq};")
    print(f"const V1_EXPECTED_SIGMA_SCALED: i64 = {v1_expected_from_scaled_int};")
    print(f"// Tolerance: 0.1% of expected = {int(round(v1_expected_from_scaled_int * 0.001))}")
    print()

    # --- Vector 2: high-vol realistic crypto (~80% annual) over 720 samples ---
    # sigma_hourly = 0.80 / sqrt(8760) ≈ 0.00854466
    random.seed(123)
    target_annual_2 = 0.80
    sigma_h_2 = target_annual_2 / math.sqrt(HOURS_PER_YEAR)
    v2_returns_float = [random.gauss(0.0, sigma_h_2) for _ in range(720)]
    v2_returns_scaled = [scaled_int(r) for r in v2_returns_float]
    v2_returns_back = [r / SCALE for r in v2_returns_scaled]
    v2_expected = annualized_vol(v2_returns_back)
    v2_expected_scaled = scaled_int(v2_expected)
    v2_sum = sum(v2_returns_scaled)
    v2_sum_sq = sum(x * x for x in v2_returns_scaled)
    print(f"// Vector 2 (720 samples, ~80% annual crypto vol):")
    print(f"//   target annual sigma:                 {target_annual_2}")
    print(f"//   actual annualized sigma:             {v2_expected:.6f}")
    print(f"//   scaled expected:                     {v2_expected_scaled}")
    print(f"const V2_SAMPLE_COUNT: u16 = {len(v2_returns_scaled)};")
    print(f"const V2_SUM_LOG_RETURNS: i128 = {v2_sum};")
    print(f"const V2_SUM_LOG_RETURNS_SQ: i128 = {v2_sum_sq};")
    print(f"const V2_EXPECTED_SIGMA_SCALED: i64 = {v2_expected_scaled};")
    print()

    # --- Vector 3: low-vol realistic FX (~10% annual) over 720 samples ---
    # sigma_hourly = 0.10 / sqrt(8760) ≈ 0.00106808
    random.seed(7)
    target_annual_3 = 0.10
    sigma_h_3 = target_annual_3 / math.sqrt(HOURS_PER_YEAR)
    v3_returns_float = [random.gauss(0.0, sigma_h_3) for _ in range(720)]
    v3_returns_scaled = [scaled_int(r) for r in v3_returns_float]
    v3_returns_back = [r / SCALE for r in v3_returns_scaled]
    v3_expected = annualized_vol(v3_returns_back)
    v3_expected_scaled = scaled_int(v3_expected)
    v3_sum = sum(v3_returns_scaled)
    v3_sum_sq = sum(x * x for x in v3_returns_scaled)
    print(f"// Vector 3 (720 samples, ~10% annual FX vol):")
    print(f"//   target annual sigma:                 {target_annual_3}")
    print(f"//   actual annualized sigma:             {v3_expected:.6f}")
    print(f"//   scaled expected:                     {v3_expected_scaled}")
    print(f"const V3_SAMPLE_COUNT: u16 = {len(v3_returns_scaled)};")
    print(f"const V3_SUM_LOG_RETURNS: i128 = {v3_sum};")
    print(f"const V3_SUM_LOG_RETURNS_SQ: i128 = {v3_sum_sq};")
    print(f"const V3_EXPECTED_SIGMA_SCALED: i64 = {v3_expected_scaled};")
    print()

    # --- Constant: sqrt(8760) * SCALE -------------------------------------
    sqrt_hpy = math.sqrt(HOURS_PER_YEAR)
    sqrt_hpy_scaled = scaled_int(sqrt_hpy)
    print(f"// Verified constant: sqrt(8760) * SCALE")
    print(f"//   sqrt(8760) = {sqrt_hpy:.15f}")
    print(f"const SQRT_HOURS_PER_YEAR_SCALED_EXPECTED: i64 = {sqrt_hpy_scaled};")


if __name__ == "__main__":
    main()
