// errorDecoder.ts — IDL-driven Anchor error decoder for the Opta protocol.
//
// The on-chain error map is built ONCE at module load by parsing the
// errors[] array from the bundled Anchor IDL (app/src/idl/opta.json,
// regenerated by `anchor build` from programs/opta/src/errors.rs).
// This makes the IDL the single source of truth: when a new error
// variant ships in Rust, an IDL refresh propagates it here
// automatically with no manual edits to this file.
//
// HIGH-1 fix (audit run 7, 2026-05-04): the previous static map was
// authored against the v1 P2P enum and drifted across the v1→v2
// reshuffle plus three subsequent patches. 36 of 42 active codes
// displayed the message of an entirely different on-chain failure
// (e.g. PriceConfidenceTooWide → "Insufficient free collateral...").
// The runtime parse retires that drift class.

import idl from "../idl/opta.json";
import {
  ANCHOR_ERROR_BASE,
  extractProgramErrorCode,
  extractSimulationLogs,
  GENERIC_FAILURE_COPY,
  isNativeSolShortfall,
} from "./txFailure";

/**
 * Retain what actually failed. The 2026-08-12 incident could not be diagnosed
 * after the fact because the transaction never landed — it died in preflight, so
 * the chain has no record — and the ONLY witness, SendTransactionError.logs, was
 * discarded here. Console/structured only; never rendered.
 */
function logFailure(error: unknown, code: number): void {
  const origin = code < ANCHOR_ERROR_BASE ? "another program in this transaction" : "opta";
  const logs = extractSimulationLogs(error);
  console.warn(
    `[opta] unmapped on-chain error code ${code} (from ${origin})`,
    { code, logs: logs ?? "(none captured)", error },
  );
}

// FRIENDLY_OVERRIDES: keyed by VARIANT NAME (not code) so the override
// survives any future enum reorder. Each entry exists for one of two
// reasons:
//   1. The IDL msg is broken or technical:
//      - HolderExerciseWindowOpen — IDL has a literal "\\\n" artifact
//        from a multi-line #[msg(...)] macro in errors.rs.
//      - InvalidListingEscrow / ListingMismatch — IDL describes
//        internal PDA shape rather than what the user should do.
//   2. We have a strictly friendlier copy than the IDL's terse phrasing
//      (ListingExhausted, NotResaleSeller).
//   3. PROVENANCE (added 2026-08-13). The IDL msg names a price vendor or an
//      internal oracle mechanism, and these strings reach TOASTS. 20 of the 84
//      on-chain errors do — every Pyth*, VolOracle*, Switchboard* and Ed25519
//      variant — because errors.rs is written for engineers reading a stack
//      trace, which is the right audience for errors.rs and the wrong one for a
//      toast. The hard rule is that users never learn which oracle we use.
//
//      This was invisible until this session: the decoder's `0x1` substring bug
//      caught 0x17ad (SwitchboardVerifyFailed) FIRST and rendered it as
//      "Insufficient SOL", so the vendor name never surfaced. Fixing the
//      substring bug exposed it — a fix uncovering the thing it was accidentally
//      hiding. Both are corrected together; shipping one without the other would
//      trade a wrong sentence for a forbidden one.
//
//      Overrides are keyed by VARIANT NAME, so an IDL refresh that renumbers or
//      rewords these cannot reintroduce the leak.
// Any variant NOT in this map falls through to its IDL msg verbatim —
// sane-by-default. New on-chain variants automatically get a readable
// string with no code change required here.
const FRIENDLY_OVERRIDES: Record<string, string> = {
  HolderExerciseWindowOpen:
    "Withdraw opens 24h after expiry — buyers need time to exercise first.",
  ListingExhausted:
    "Not enough contracts left in this listing — someone may have just bought.",
  NotResaleSeller: "Only the listing's seller can cancel it.",
  InvalidListingEscrow: "Listing data mismatch — please refresh and try again.",
  ListingMismatch: "Listing data mismatch — please refresh and try again.",
  InvalidEpochExpiry: "This tenor is too soon — pick a later expiry.",

  // ---- provenance overrides (reason 3) ------------------------------------
  // Settlement-price freshness. The user's action is the same in every case:
  // wait a moment and retry.
  PriceUpdateBeforeExpiry: "Price data for this expiry isn't available yet — try again shortly.",
  PriceUpdateTooFarFromExpiry: "Price data for this expiry is outside the settlement window.",
  PriceConfidenceTooWide: "The settlement price is too uncertain right now — try again shortly.",
  InvalidPythFeedId: "This market has no valid price feed.",

  // Volatility-model state. Users know this surface as "pricing warming up".
  VolOracleNotInitialized: "Pricing for this market is still warming up — this takes about 2 minutes.",
  VolOracleWarmup: "Pricing for this market is still warming up.",
  VolOracleStale: "Pricing data is stale — try again shortly.",
  VolOraclePushTooSoon: "Pricing was updated recently — try again shortly.",
  VolOraclePriceStale: "Price unavailable — try again.",
  VolOracleInvalidSpot: "Price unavailable — try again.",
  VolOracleMathError: "Pricing could not be computed for this market.",

  // Pull-oracle proof path. All of these mean one thing to a user: the price
  // attached to this transaction was not usable.
  SwitchboardVerifyFailed: "Price unavailable — try again.",
  SwitchboardFeedNotFound: "Price unavailable — try again.",
  SwitchboardInsufficientSamples: "Price unavailable — try again.",
  SwitchboardSettleWindowElapsed: "The settlement window for this expiry has passed.",
  PriceUpdateMissing: "Price unavailable — try again.",
  SwitchboardAccountsMissing: "Price unavailable — try again.",
  NoEd25519Instruction: "Price unavailable — try again.",
  InvalidSwitchboardSysvar: "Price unavailable — try again.",
  InvalidOracleSource: "This market's price source could not be determined.",
};

// Build code→message map at module load by walking idl.errors[]. The
// cast is defensive: the IDL JSON's literal-types are usable directly,
// but pinning the shape makes the parse contract explicit and
// insulates this file against future IDL schema tweaks.
type IdlError = { code: number; name: string; msg: string };
const CUSTOM_ERRORS: Record<number, string> = (() => {
  const map: Record<number, string> = {};
  for (const e of (idl.errors ?? []) as ReadonlyArray<IdlError>) {
    map[e.code] = FRIENDLY_OVERRIDES[e.name] ?? e.msg;
  }
  return map;
})();

// MED-8 — single source of truth for wallet-replay sentinel detection.
//
// The wallet-replay artifact (an optimistic resimulate against a lagged
// RPC pool) surfaces as one of two strings depending on which catch
// site receives it:
//   - Direct catches (no rethrow): err.message contains the raw RPC
//     string "already been processed".
//   - Rethrow chain catches (purchaseFlow / resaleBuyFlow / writeSubmit
//     all rethrow with `new Error(decodeError(err))`): err.message
//     contains the decoded string "already confirmed".
// Either path resolves to the same boolean. Decoupling sentinel
// detection from the decoder string means future copy changes to
// "Transaction already confirmed." (HIGH-1's IDL-driven decoder is
// open to such tweaks) cannot silently regress the BTC PUT race
// recovery shipped 2026-05-02.
export function isWalletReplay(error: any): boolean {
  const msg = String(error?.message ?? error ?? "");
  return msg.includes("already been processed") || msg.includes("already confirmed");
}

export function decodeError(error: any): string {
  if (!error) return "Unknown error";
  const msg = error?.message || error?.toString() || "";

  // Wallet-replay artifact — wallet's optimistic resimulate against
  // a lagged RPC pool sees the now-landed tx as "already processed".
  // Decode to a stable substring ("already confirmed") that consumer
  // catch blocks detect to upgrade the error path to success +
  // refetch instead of showing a "failed" toast.
  //
  // PRESERVED BYTE-IDENTICAL across the HIGH-1 rewrite. 8 consumer
  // sites match this string via `.includes("already confirmed")` —
  // BuyModal:217, useWriteSubmit:100, usePortfolioActions:77/112/147/178,
  // useWriterActions:170/256/347. Changing the returned string here
  // silently regresses the BTC PUT race-recovery shipped 2026-05-02.
  if (msg.includes("already been processed")) {
    return "Transaction already confirmed.";
  }

  // User rejection
  if (msg.includes("User rejected")) return "Transaction rejected in wallet.";

  // ── ON-CHAIN ERROR CODE — read as a NUMBER, before any text matching ──────
  //
  // ORDER IS THE FIX. This block used to sit BELOW two text tests, the first of
  // which was `msg.includes("0x1")`. That is a substring match, and
  // `custom program error: 0x17ad` — a stale price quote, Opta 6061 — contains
  // it, so every stale quote told the user to top up SOL they already had.
  // Codes are numbers; extract once, compare numerically, and let the mapped
  // message win before any heuristic gets a turn.
  const code = extractProgramErrorCode(msg);
  if (code !== null) {
    if (CUSTOM_ERRORS[code]) return CUSTOM_ERRORS[code];

    // Below the Anchor user-error base this did NOT come from Opta — it came
    // from another program in the same transaction (SPL Token, a precompile).
    // We have no mapping and no business inventing one.
    logFailure(error, code);
    return GENERIC_FAILURE_COPY;
  }

  // ── NATIVE SOL vs TOKEN BALANCE ───────────────────────────────────────────
  // These are different problems with different remedies, and the old code
  // collapsed them: a token-program "insufficient funds" (a USDC shortfall in a
  // vault or wallet) was reported as missing SOL.
  if (isNativeSolShortfall(msg)) return "Insufficient SOL for transaction fees.";
  if (msg.includes("insufficient") && msg.includes("token")) {
    return "Insufficient USDC balance. Use the faucet to get test USDC.";
  }

  // Truncate long messages
  if (msg.length > 150) return msg.slice(0, 147) + "...";
  return msg;
}
