// errorDecoder.ts — IDL-driven Anchor error decoder for the Opta protocol.
//
// The on-chain error map is built ONCE at module load by parsing the
// errors[] array from the bundled Anchor IDL (app/src/idl/opta.json,
// regenerated by `anchor build` from programs/opta/src/errors.rs).
// This makes the IDL the single source of truth: when a new error
// variant ships in Rust, an IDL refresh propagates it here
// automatically with no manual edits to this file.
//
// HIGH-1 fix (audit run 7, 2026-05-04): the previous static map was
// authored against the v1 P2P enum and drifted across the v1→v2
// reshuffle plus three subsequent patches. 36 of 42 active codes
// displayed the message of an entirely different on-chain failure
// (e.g. PriceConfidenceTooWide → "Insufficient free collateral...").
// The runtime parse retires that drift class.

import idl from "../idl/opta.json";

// FRIENDLY_OVERRIDES: keyed by VARIANT NAME (not code) so the override
// survives any future enum reorder. Each entry exists for one of two
// reasons:
//   1. The IDL msg is broken or technical:
//      - HolderExerciseWindowOpen — IDL has a literal "\\\n" artifact
//        from a multi-line #[msg(...)] macro in errors.rs.
//      - InvalidListingEscrow / ListingMismatch — IDL describes
//        internal PDA shape rather than what the user should do.
//   2. We have a strictly friendlier copy than the IDL's terse phrasing
//      (ListingExhausted, NotResaleSeller).
// Any variant NOT in this map falls through to its IDL msg verbatim —
// sane-by-default. New on-chain variants automatically get a readable
// string with no code change required here.
const FRIENDLY_OVERRIDES: Record<string, string> = {
  HolderExerciseWindowOpen:
    "Withdraw opens 24h after expiry — buyers need time to exercise first.",
  ListingExhausted:
    "Not enough contracts left in this listing — someone may have just bought.",
  NotResaleSeller: "Only the listing's seller can cancel it.",
  InvalidListingEscrow: "Listing data mismatch — please refresh and try again.",
  ListingMismatch: "Listing data mismatch — please refresh and try again.",
  InvalidEpochExpiry: "This tenor is too soon — pick a later expiry.",
};

// Build code→message map at module load by walking idl.errors[]. The
// cast is defensive: the IDL JSON's literal-types are usable directly,
// but pinning the shape makes the parse contract explicit and
// insulates this file against future IDL schema tweaks.
type IdlError = { code: number; name: string; msg: string };
const CUSTOM_ERRORS: Record<number, string> = (() => {
  const map: Record<number, string> = {};
  for (const e of (idl.errors ?? []) as ReadonlyArray<IdlError>) {
    map[e.code] = FRIENDLY_OVERRIDES[e.name] ?? e.msg;
  }
  return map;
})();

// MED-8 — single source of truth for wallet-replay sentinel detection.
//
// The wallet-replay artifact (an optimistic resimulate against a lagged
// RPC pool) surfaces as one of two strings depending on which catch
// site receives it:
//   - Direct catches (no rethrow): err.message contains the raw RPC
//     string "already been processed".
//   - Rethrow chain catches (purchaseFlow / resaleBuyFlow / writeSubmit
//     all rethrow with `new Error(decodeError(err))`): err.message
//     contains the decoded string "already confirmed".
// Either path resolves to the same boolean. Decoupling sentinel
// detection from the decoder string means future copy changes to
// "Transaction already confirmed." (HIGH-1's IDL-driven decoder is
// open to such tweaks) cannot silently regress the BTC PUT race
// recovery shipped 2026-05-02.
export function isWalletReplay(error: any): boolean {
  const msg = String(error?.message ?? error ?? "");
  return msg.includes("already been processed") || msg.includes("already confirmed");
}

export function decodeError(error: any): string {
  if (!error) return "Unknown error";
  const msg = error?.message || error?.toString() || "";

  // Wallet-replay artifact — wallet's optimistic resimulate against
  // a lagged RPC pool sees the now-landed tx as "already processed".
  // Decode to a stable substring ("already confirmed") that consumer
  // catch blocks detect to upgrade the error path to success +
  // refetch instead of showing a "failed" toast.
  //
  // PRESERVED BYTE-IDENTICAL across the HIGH-1 rewrite. 8 consumer
  // sites match this string via `.includes("already confirmed")` —
  // BuyModal:217, useWriteSubmit:100, usePortfolioActions:77/112/147/178,
  // useWriterActions:170/256/347. Changing the returned string here
  // silently regresses the BTC PUT race-recovery shipped 2026-05-02.
  if (msg.includes("already been processed")) {
    return "Transaction already confirmed.";
  }

  // User rejection
  if (msg.includes("User rejected")) return "Transaction rejected in wallet.";

  // Insufficient SOL
  if (msg.includes("insufficient funds") || msg.includes("0x1")) return "Insufficient SOL for transaction fees.";

  // Insufficient token balance
  if (msg.includes("insufficient") && msg.includes("token")) return "Insufficient USDC balance. Use the faucet to get test USDC.";

  // Extract Anchor custom error code
  const codeMatch = msg.match(/custom program error: 0x([0-9a-fA-F]+)/);
  if (codeMatch) {
    const code = parseInt(codeMatch[1], 16);
    if (CUSTOM_ERRORS[code]) return CUSTOM_ERRORS[code];
    console.warn(
      `[opta] unmapped on-chain error code ${code} — IDL may need refresh`,
      error,
    );
    return `Program error ${code}`;
  }

  // Anchor error code in decimal
  const anchorMatch = msg.match(/Error Number: (\d+)/);
  if (anchorMatch) {
    const code = parseInt(anchorMatch[1]);
    if (CUSTOM_ERRORS[code]) return CUSTOM_ERRORS[code];
    console.warn(
      `[opta] unmapped on-chain error code ${code} — IDL may need refresh`,
      error,
    );
    return `Program error ${code}`;
  }

  // Truncate long messages
  if (msg.length > 150) return msg.slice(0, 147) + "...";
  return msg;
}
